//user constants
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const SHARE_EMAIL_REQUEST = "SHARE_EMAIL_REQUEST";
export const SHARE_EMAIL_SUCCESS = "SHARE_EMAIL_SUCCESS";
export const SHARE_EMAIL_FAILED = "SHARE_EMAIL_FAILED";
export const ADD_EMAIL_REQUEST = "ADD_EMAIL_REQUEST";
export const ADD_EMAIL_SUCCESS = "ADD_EMAIL_SUCCESS";
export const ADD_EMAIL_FAILED = "ADD_EMAIL_FAILED";
export const LOAD_EMAILS_REQUEST = "LOAD_EMAILS_REQUEST";
export const LOAD_EMAILS_SUCCESS = "LOAD_EMAILS_SUCCESS";
export const LOAD_EMAILS_FAILED = "LOAD_EMAILS_FAILED";
